# Data
data_dir: ../data/raw/MIT
training_csv: training.csv
validation_csv: validation.csv
no_classes: 8

# Model
model: resnet10
clip_length: 8  # how many frames per clip window
clip_stride: 8  # how many frames to slide the window

# Training
epochs: 10
batch_size: 4

# Optimizer
lr: 0.01
momentum: 0.9

# Augmentation
transform:
  scale: 128

# Logging
log_interval: 10
to_file: False
